device: "cuda"
model_dir: "./model_dir_MCTS_1d_static"
log_dir: "./log_dir_MCTS_1d_static"
lr: 0.0001
batch_size: 2000
plan_type: 0 ##0: sin 1: Guassian 2:step
Random_seed: 1
Replay_buffer_size: 50000
N_iteration: 10000
update_traget_period: 200
rollout: 20
UCB_CONSTANT: 0.5