Random_seed: 1
model_dir: "./model_dir_PPO_1d_dynamic"
log_dir: "./log_dir_PPO_1d_dynamic"
gamma: 0.99
n_steps: 100000
ent_coef: 0.01
learning_rate: 0.00025
vf_coef: 0.5
cliprange: 0.1
nminibatches: 100
noptepochs: 4