device: "cuda"
model_dir: "./model_dir_DRQN_Lnet_1d_dynamic"
log_dir: "./log_dir_DRQN_Lnet_1d_dynamic"
lr: 0.00005
batch_size: 64
plan_type: 0 ##0: sin 
Random_seed: 1
Replay_buffer_size: 1000
N_iteration: 10000
update_traget_period: 200
pretrainmodel: model_dynamic_00630000.pth