device: "cuda"
model_dir: "./model_dir_DQN_Lnet_3d_static"
log_dir: "./log_dir_DQN_3d_Lnet_static"
lr: 0.00001
batch_size: 2000
plan_type: 1  ##0: dense 1: sparse
Random_seed: 1
Replay_buffer_size: 50000
N_iteration: 10000
update_traget_period: 200
pretrainmodel: model_staticsparse_01000000.pth